version: '3.4'

services:
  contactsguide.mongodb.contact.api:
    image: mongo
    container_name: contactsguide.mongodb.contact.api
    restart: always
    environment:
     - MONGO_INITDB_DATABASE=ContactsGuideDb
    ports:
     - 27017:27017
    volumes:
     - contactapidb_volume:/data/db
    networks:
     - custom-network
  contactsguide.mongodb.report.api:
    image: mongo
    container_name: contactsguide.mongodb.report.api
    restart: always
    environment:
     - MONGO_INITDB_DATABASE=ContactsGuideReportDb
    ports:
      - 27018:27017
    volumes:
     - reportapidb_volume:/data/db
    networks:
      - custom-network
  contactsguide.rabbitmq:
    image: rabbitmq:3-management
    container_name: contactsguide.rabbitmq
    restart: always
    hostname: ContactGuideMQ
    labels:
      NAME: "ContactGuideMQ"
    ports:
     - 5672:5672
     - 15672:15672
    environment:
     RABBITMQ_DEFAULT_USER: admin
     RABBITMQ_DEFAULT_PASS: 123456
    networks:
      - custom-network
  contactsguide.report.api:
    image: burakhayirli/dotnetcore-contactsguide-microservice-reportapi
    build:
      context: .
      dockerfile: src/Services/Report/Report.Api/Dockerfile
    ports:
     - 5006:80
    volumes:
     - reportapi_volume:/app/wwwroot/documents
    networks:
     - custom-network
    depends_on:
     - contactsguide.mongodb.report.api
     - contactsguide.rabbitmq
  contactsguide.contact.api:
    image: burakhayirli/dotnetcore-contactsguide-microservice-contactapi
    build:
      context: .
      dockerfile: src/Services/Contact/Contact.Api/Dockerfile
    ports:
      - 5005:80
    networks:
      - custom-network
    depends_on:
      - contactsguide.mongodb.contact.api
volumes:
  contactapidb_volume:
  reportapidb_volume:
  reportapi_volume:
networks:
  custom-network:

